### PR TITLE
Fix: Support querying document by Id directly rather than using a query

### LINKED ISSUE #115: QueryById should do direct lookup in Cosmos
<see title>

### LINKED ISSUE #276: make this return single entities when only one is asked for eg. /movies/id
https://github.com/microsoft/helium/blob/f2a91e450e7cc2896ee9cc1e6f1c1a9c710bd942/src/app/controllers/movie.ts#L146

### PR DESCRIPTION
**Pull request by seushermsft**
**What this PR does / why we need it**:

This PR enables us to do a direct lookup of a document rather than a query. This reduces the RUs used for a single document look up.

closes #115 
closes #276

**Special notes for your reviewer**:

Running `docker-compose build` and `docker-compose up` will reveal that RU cost in the console. For a getDocument call, you will see a line similar to:

> getDocument RU Cost: 1

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains tests

### CODE REVIEW

File: src/app/tests/actor.integration.ts [hunk 1]
```diff
@@ -44,9 +44,8 @@ describe("Testing Actor Controller Methods", () => {
           .then((getResponse) => {
             chai.expect(getResponse).to.have.status(200);
             const body = getResponse.body;
-            chai.assert.isArray(body);
-            chai.assert.isAtLeast(body.length, 1);
-            const id = body[0].actorId;
+            chai.assert.isNotArray(body);
```
Comment (frodopwns) [inline src/app/tests/actor.integration.ts]: `isObject()` is also an options
